### ISSUE TITLE
Problem with pages > 100

### ISSUE THREAD

**Issue by Rkrushanovskij** [ipfs-search/ipfs-search-api#9]
Hello!
I`m trying to use your API for ipfs-search.

<details><summary>API response on https://api.ipfs-search.com/v1/search?q=ti&page=0</summary>
<pre>
{ total: 18710,
  max_score: 71.93868,
  hits:
   [ { hash: 'QmQnoT4ZpHtNB4fBzcX1s1BmiHpSr2iutNsfQiZZDht3s4',
       title: '23px-Tobu_Isesaki_Line_(<em>TI</em>)_symbol.svg.png',
       description: null,
       type: 'file',
       size: 616,
       'first-seen': '2019-01-12T00:35:20Z',
       'last-seen': '2019-01-23T11:36:23Z',
       score: 71.93868,
       mimetype: 'image/png' },
       ...
     { hash: 'QmWZ6jpEvZ5gmjjT13GFj3QovoV3Cs4bHDCueQipgKAL4d',
       title: '<em>TI</em>',
       description: null,
       type: 'directory',
       size: 0,
       'last-seen': '2019-01-10T22:18:35Z',
       score: 52.76256 } ],
  page_size: 15,
  page_count: 1248 }
</pre></details>
<details><summary>API response on https://api.ipfs-search.com/v1/search?q=ti&page=1247</summary>
<pre>
{ error: 'Cannot read property \'message\' of undefined' }
</pre></details>
<details><summary>API response on https://api.ipfs-search.com/v1/search?q=ti&page=1246</summary>
<pre>
{ error: 'Cannot read property \'message\' of undefined' }
</pre></details>

As you can see, i\`m trying to get page inside `page_count` boundaries but it is unsuccessful.
Could you help me please?

**Comment by Rkrushanovskij** [comment]
@dokterbob 
99 OK
100 OK
101 `{ error: 'Cannot read property \'message\' of undefined' }`

**Comment by dokterbob** [comment]
Feel free to dive into the code. I think there’s a bug where the error message doesn’t render properly. I don’t think we want pages > 100 for performance reasons.

**Comment by Rkrushanovskij** [comment]
Ok, so i should limit my requests by 100 page max, right?

**Comment by dokterbob** [comment]
Yep. That’s wise. It’s just that paging to high page numbers is heavy on server load.
